// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/art-Hasan/gqlgen-todos/graph"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func Service() (service, error) {
	db := newDB()
	client, err := newEnt(db)
	if err != nil {
		return service{}, err
	}
	resolverRoot := graph.NewResolver(client)
	mux := newRouter(resolverRoot)
	addr := newAddr()
	mainService := newService(client, mux, addr)
	return mainService, nil
}
